### ISSUE TITLE
Scramble api Documenation

### ISSUE THREAD

**Issue by Hankq1** [Tiskiel/catGenerator#2]
hey, i have a question . could you help me with scramble api documentation 🙏  .. im facing issues.

**Comment by Tiskiel** [comment]
Hi @Hankq1 , 

You are to a bad repository. I've stared the scramble api repository to learn it later. I didn't use it at the moment. If you have an issue, I invite you to check the discussion to it repository [here](https://github.com/dedoc/scramble/discussions)

Have a nice day
